name = "ohmylife"
compatibility_date = "2024-11-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "ohmylife-db"
database_id = "xxxx-xxxx-xxxx-xxxx" # Placeholder, will be updated after creation
migrations_dir = "drizzle"
